#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Statistical Mechanics for Chemistry and Biology  # The title of the book. Will be placed in the left navbar.
author                      : Davit Potoyan  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.jpg  # A path to the book logo

# Information about where the book exists on the web
repository:
  url                       : https://github.com/DPotoyan/Statmech4ChemBio  # Online location of your book
  branch                    : master  # Which branch of the repository should be used when creating links (optional)
  #path_to_book              : path/to/book  # Optional path to your book, relative to the repository root
  
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab"